CREATE TABLE IF NOT EXISTS tasks ( 
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL, 
  status TEXT
);

CREATE TABLE IF NOT EXISTS team_members (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS task_assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id INTEGER,
  member_id INTEGER,
  FOREIGN KEY (task_id) REFERENCES tasks(id),
  FOREIGN KEY (member_id) REFERENCES team_members(id)
);